# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pykanbanflow
from pykanbanflow.models.task_label import TaskLabel  # noqa: E501
from pykanbanflow.rest import ApiException


class TestTaskLabel(unittest.TestCase):
    """TaskLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskLabel(self):
        """Test TaskLabel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pykanbanflow.models.task_label.TaskLabel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
