# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pykanbanflow
from pykanbanflow.models.create_task_response import CreateTaskResponse  # noqa: E501
from pykanbanflow.rest import ApiException


class TestCreateTaskResponse(unittest.TestCase):
    """CreateTaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTaskResponse(self):
        """Test CreateTaskResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pykanbanflow.models.create_task_response.CreateTaskResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
