# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pykanbanflow
from pykanbanflow.models.swimlane import Swimlane  # noqa: E501
from pykanbanflow.rest import ApiException


class TestSwimlane(unittest.TestCase):
    """Swimlane unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSwimlane(self):
        """Test Swimlane"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pykanbanflow.models.swimlane.Swimlane()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
