# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pykanbanflow
from pykanbanflow.models.column import Column  # noqa: E501
from pykanbanflow.rest import ApiException


class TestColumn(unittest.TestCase):
    """Column unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumn(self):
        """Test Column"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pykanbanflow.models.column.Column()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
