# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pykanbanflow
from pykanbanflow.models.tasks_by_column import TasksByColumn  # noqa: E501
from pykanbanflow.rest import ApiException


class TestTasksByColumn(unittest.TestCase):
    """TasksByColumn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTasksByColumn(self):
        """Test TasksByColumn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pykanbanflow.models.tasks_by_column.TasksByColumn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
