# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pykanbanflow
from pykanbanflow.api.default_api import DefaultApi  # noqa: E501
from pykanbanflow.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_board(self):
        """Test case for get_board

        Returns the structure of the board belonging to the token.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
