# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Board(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'columns': 'list[Column]',
        'swimlanes': 'list[Swimlane]',
        'colors': 'list[Color]'
    }

    attribute_map = {
        'id': '_id',
        'name': 'name',
        'columns': 'columns',
        'swimlanes': 'swimlanes',
        'colors': 'colors'
    }

    def __init__(self, id=None, name=None, columns=None, swimlanes=None, colors=None):  # noqa: E501
        """Board - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._columns = None
        self._swimlanes = None
        self._colors = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.columns = columns
        if swimlanes is not None:
            self.swimlanes = swimlanes
        self.colors = colors

    @property
    def id(self):
        """Gets the id of this Board.  # noqa: E501


        :return: The id of this Board.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Board.


        :param id: The id of this Board.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Board.  # noqa: E501


        :return: The name of this Board.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Board.


        :param name: The name of this Board.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def columns(self):
        """Gets the columns of this Board.  # noqa: E501


        :return: The columns of this Board.  # noqa: E501
        :rtype: list[Column]
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """Sets the columns of this Board.


        :param columns: The columns of this Board.  # noqa: E501
        :type: list[Column]
        """
        if columns is None:
            raise ValueError("Invalid value for `columns`, must not be `None`")  # noqa: E501

        self._columns = columns

    @property
    def swimlanes(self):
        """Gets the swimlanes of this Board.  # noqa: E501


        :return: The swimlanes of this Board.  # noqa: E501
        :rtype: list[Swimlane]
        """
        return self._swimlanes

    @swimlanes.setter
    def swimlanes(self, swimlanes):
        """Sets the swimlanes of this Board.


        :param swimlanes: The swimlanes of this Board.  # noqa: E501
        :type: list[Swimlane]
        """

        self._swimlanes = swimlanes

    @property
    def colors(self):
        """Gets the colors of this Board.  # noqa: E501


        :return: The colors of this Board.  # noqa: E501
        :rtype: list[Color]
        """
        return self._colors

    @colors.setter
    def colors(self, colors):
        """Sets the colors of this Board.


        :param colors: The colors of this Board.  # noqa: E501
        :type: list[Color]
        """
        if colors is None:
            raise ValueError("Invalid value for `colors`, must not be `None`")  # noqa: E501

        self._colors = colors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Board, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Board):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
