# coding: utf-8

"""
    Kanbanflow API

    Lean project management. Simplified.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskSubTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'finished': 'bool',
        'due_date_timestamp': 'str',
        'due_date_timestamp_local': 'str'
    }

    attribute_map = {
        'name': 'name',
        'finished': 'finished',
        'due_date_timestamp': 'dueDateTimestamp',
        'due_date_timestamp_local': 'dueDateTimestampLocal'
    }

    def __init__(self, name=None, finished=None, due_date_timestamp=None, due_date_timestamp_local=None):  # noqa: E501
        """TaskSubTask - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._finished = None
        self._due_date_timestamp = None
        self._due_date_timestamp_local = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if finished is not None:
            self.finished = finished
        if due_date_timestamp is not None:
            self.due_date_timestamp = due_date_timestamp
        if due_date_timestamp_local is not None:
            self.due_date_timestamp_local = due_date_timestamp_local

    @property
    def name(self):
        """Gets the name of this TaskSubTask.  # noqa: E501


        :return: The name of this TaskSubTask.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TaskSubTask.


        :param name: The name of this TaskSubTask.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def finished(self):
        """Gets the finished of this TaskSubTask.  # noqa: E501


        :return: The finished of this TaskSubTask.  # noqa: E501
        :rtype: bool
        """
        return self._finished

    @finished.setter
    def finished(self, finished):
        """Sets the finished of this TaskSubTask.


        :param finished: The finished of this TaskSubTask.  # noqa: E501
        :type: bool
        """

        self._finished = finished

    @property
    def due_date_timestamp(self):
        """Gets the due_date_timestamp of this TaskSubTask.  # noqa: E501


        :return: The due_date_timestamp of this TaskSubTask.  # noqa: E501
        :rtype: str
        """
        return self._due_date_timestamp

    @due_date_timestamp.setter
    def due_date_timestamp(self, due_date_timestamp):
        """Sets the due_date_timestamp of this TaskSubTask.


        :param due_date_timestamp: The due_date_timestamp of this TaskSubTask.  # noqa: E501
        :type: str
        """

        self._due_date_timestamp = due_date_timestamp

    @property
    def due_date_timestamp_local(self):
        """Gets the due_date_timestamp_local of this TaskSubTask.  # noqa: E501


        :return: The due_date_timestamp_local of this TaskSubTask.  # noqa: E501
        :rtype: str
        """
        return self._due_date_timestamp_local

    @due_date_timestamp_local.setter
    def due_date_timestamp_local(self, due_date_timestamp_local):
        """Sets the due_date_timestamp_local of this TaskSubTask.


        :param due_date_timestamp_local: The due_date_timestamp_local of this TaskSubTask.  # noqa: E501
        :type: str
        """

        self._due_date_timestamp_local = due_date_timestamp_local

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskSubTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskSubTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
